export const mockData = [
    {
      id: 1,
      title: "Amazon Gift Card",
      description: "Shop millions of items on Amazon.",
      price: "$25",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16AVuGC1NkJwr5L2ElgOK418ecB6SU73szX0iQ",
    },
    {
      id: 2,
      title: "Google Play Gift Card",
      description: "Buy apps, games, and more on Google Play.",
      price: "$50",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16qFyXnKWrRlfHQphucbwUPTO8ENWtj7kCIGda",
    },
    {
      id: 3,
      title: "Apple Gift Card",
      description: "Use it for apps, music, and more.",
      price: "$100",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16mAzePhuo16DHgc4KxiJIG7PXUsTVkbuYvA9p",
    },
    {
      id: 4,
      title: "Netflix Gift Card",
      description: "Stream your favorite shows and movies.",
      price: "$30",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16c5ORoj4HaCQ2jqS8EpzWBALFTYR7wosi3kXe",
    },
    {
      id: 5,
      title: "Spotify Gift Card",
      description: "Listen to your favorite music ad-free.",
      price: "$15",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16m0CmDwuo16DHgc4KxiJIG7PXUsTVkbuYvA9p",
    },
    {
      id: 6,
      title: "Starbucks Gift Card",
      description: "Enjoy your favorite drinks and treats.",
      price: "$20",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16FEZqD429zZSuJgUB9t1HTC27xI5yFiAs3jcN",
    },
    {
      id: 7,
      title: "Xbox Gift Card",
      description: "Buy games, apps, and entertainment.",
      price: "$60",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16TQJQTkrIoiLy2v0j7kFehrYw6zZV4NQUX1R5",
    },
    {
      id: 8,
      title: "PlayStation Store Gift Card",
      description: "Get the latest games and add-ons.",
      price: "$75",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16lMcYuo7nCTVO0qHuhNM2tBjcWapAgUGJoPbk",
    },
    {
      id: 10,
      title: "Uber Gift Card",
      description: "Ride or eat with Uber and Uber Eats.",
      price: "$25",
      imageUrl: "https://69ornd2uel.ufs.sh/f/oagqtr3QMV16E7dI0O2zc4TpiD0nvSC9Vqa3XeW58ZlfMJ6b",
    },
  ];